# Generated by Django 4.1.3 on 2022-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
