# Generated by Django 4.1.3 on 2022-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_squad_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='notes',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
