# Generated by Django 4.1.3 on 2022-12-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_squad_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=1)),
                ('absent_player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absent_player', to='planner.player')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.game')),
                ('substitute', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute', to='planner.player')),
            ],
        ),
    ]
