# Generated by Django 4.1.3 on 2022-12-04 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='absent_player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absent_player', to='planner.player'),
        ),
        migrations.AddField(
            model_name='squad',
            name='substitution_order',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
    ]
